import rmapy
import rmapy.document
import subprocess
import zipfile
import os

import sys
sys.path.append("/home/pi/easy-rmapy")
import easyrmapy as er

# Parameters:
#upload_path = "generated by rest of script."
#hcl_file = "notes.hcl"


def make_rm_notes(upload_path, hcl_file):
    # first generate file for today:
    outfilename = "notes.zip"
    drawj2d = ["drawj2d", "-Trmapi", hcl_file, "-o", outfilename]
    result = subprocess.check_output( drawj2d, text=True, )
    generated = "./{0}".format(outfilename)

    # find correct UUID (nessecary due to bug in rmapy)
    zip = zipfile.ZipFile(generated)
    names = zip.namelist()
    uuid = os.path.splitext(names[0])[0]

    # upload the generated zip
    rm = er.ReMarkable()
    zipdoc = rmapy.document.ZipDocument(file=generated,_id=uuid)
    parentID = rm.path_to_ID(upload_path)
    dirobj = rm.rma.get_doc(parentID)
    result = rm.rma.upload(zipdoc,dirobj)
    if not result:
        raise ValueError("upload failed :.(")
    
    # Finally, rename file to notes
    doc = rm.rma.get_doc(uuid)
    doc.VissibleName = "Notes"
    rm.rma.update_metadata(doc)



